# Generated by Django 5.2.7 on 2025-10-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitabilityCalculation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_month', models.DateField(verbose_name='Период')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая выручка')),
                ('total_miles', models.IntegerField(verbose_name='Общий пробег')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Зарплата')),
                ('fuel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Топливо')),
                ('variable_tolls', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Платные дороги (переменные)')),
                ('common_ifta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IFTA')),
                ('common_insurance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общее страхование')),
                ('common_eld', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ELD')),
                ('common_tablet', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Планшет')),
                ('common_tolls', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Платные дороги (общие)')),
                ('truck_payment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Платеж за трак')),
                ('trailer_payment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Платеж за прицеп')),
                ('truck_insurance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Страхование трака')),
                ('trailer_insurance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Страхование прицепа')),
                ('total_variable_costs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общие переменные затраты')),
                ('total_fixed_costs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общие фиксированные затраты')),
                ('total_costs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общие затраты')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Прибыль')),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Маржа прибыли (%)')),
                ('profit_per_mile', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Прибыль за милю')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck', verbose_name='Трак')),
            ],
            options={
                'verbose_name': 'Расчет прибыльности',
                'verbose_name_plural': 'Расчеты прибыльности',
                'db_table': 'profitability_calculation',
                'ordering': ['-period_month', 'truck'],
                'unique_together': {('truck', 'period_month')},
            },
        ),
    ]
