# Generated by Django 5.2.7 on 2025-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitabilitycalculation',
            name='period_month',
            field=models.DateTimeField(verbose_name='Период (дата и время)'),
        ),
    ]
