# Generated by Django 5.2.7 on 2025-10-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snapshots', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCostsCommon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ifta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IFTA')),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Страхование')),
                ('eld', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ELD')),
                ('tablet', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Планшет')),
                ('tolls', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Платные дороги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Общие фиксированные стоимости',
                'verbose_name_plural': 'Общие фиксированные стоимости',
                'db_table': 'fixed_costs_common',
            },
        ),
        migrations.CreateModel(
            name='FixedCostsTruck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('truck_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Платеж за трак')),
                ('trailer_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Платеж за прицеп')),
                ('physical_damage_insurance_truck', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Страхование физического ущерба трака')),
                ('physical_damage_insurance_trailer', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Страхование физического ущерба прицепа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucks.truck', verbose_name='Трак')),
            ],
            options={
                'verbose_name': 'Фиксированные стоимости трака',
                'verbose_name_plural': 'Фиксированные стоимости траков',
                'db_table': 'fixed_costs_truck',
                'unique_together': {('truck',)},
            },
        ),
        migrations.CreateModel(
            name='TruckVariableCosts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_month', models.DateField(verbose_name='Период (месяц)')),
                ('driver_name', models.TextField(blank=True, null=True, verbose_name='Имя водителя')),
                ('total_rev', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая выручка')),
                ('total_miles', models.IntegerField(default=0, verbose_name='Общий пробег')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Зарплата')),
                ('fuel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Топливо')),
                ('tolls', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Платные дороги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cost_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshots.costsnapshot', verbose_name='Снимок фиксированных стоимостей')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck', verbose_name='Трак')),
            ],
            options={
                'verbose_name': 'Переменные затраты трака',
                'verbose_name_plural': 'Переменные затраты траков',
                'db_table': 'truck_variable_costs',
                'ordering': ['-period_month', 'truck'],
                'unique_together': {('period_month', 'truck')},
            },
        ),
    ]
