# Generated by Django 5.2.7 on 2025-10-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcoststruck',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trucks.truck', verbose_name='Трак'),
        ),
    ]
