# Generated by Django 5.2.7 on 2025-10-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_fixedcoststruck_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckvariablecosts',
            name='period_month',
            field=models.DateTimeField(verbose_name='Период (дата и время)'),
        ),
    ]
