# Generated by Django 5.2.7 on 2025-10-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_alter_truckvariablecosts_period_month'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckCurrentVariableCosts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_name', models.TextField(blank=True, null=True, verbose_name='Имя водителя')),
                ('total_rev', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая выручка')),
                ('total_miles', models.IntegerField(default=0, verbose_name='Общий пробег')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Зарплата')),
                ('fuel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Топливо')),
                ('tolls', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Платные дороги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck', verbose_name='Трак')),
            ],
            options={
                'verbose_name': 'Текущие переменные затраты трака',
                'verbose_name_plural': 'Текущие переменные затраты траков',
                'db_table': 'truck_current_variable_costs',
            },
        ),
    ]
