# Generated by Django 5.2.7 on 2025-10-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_truckcurrentvariablecosts'),
        ('snapshots', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    def copy_cost_snapshot_to_snapshot(apps, schema_editor):
        TruckVariableCosts = apps.get_model('costs', 'TruckVariableCosts')
        for rec in TruckVariableCosts.objects.all():
            # Переносим старое поле cost_snapshot в новое snapshot
            if hasattr(rec, 'cost_snapshot_id') and rec.cost_snapshot_id and not rec.snapshot_id:
                rec.snapshot_id = rec.cost_snapshot_id
                rec.save(update_fields=['snapshot'])

    operations = [
        migrations.AlterModelOptions(
            name='truckvariablecosts',
            options={'ordering': ['-snapshot', 'truck'], 'verbose_name': 'Переменные затраты трака', 'verbose_name_plural': 'Переменные затраты траков'},
        ),
        migrations.AddField(
            model_name='truckvariablecosts',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshots.costsnapshot', verbose_name='Снимок (период)'),
        ),
        migrations.RunPython(copy_cost_snapshot_to_snapshot, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='truckvariablecosts',
            unique_together={('snapshot', 'truck')},
        ),
        migrations.RemoveField(
            model_name='truckvariablecosts',
            name='cost_snapshot',
        ),
        migrations.RemoveField(
            model_name='truckvariablecosts',
            name='period_month',
        ),
    ]
