# Generated by Django 5.2.7 on 2025-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tractor_no', models.TextField(unique=True, verbose_name='Номер трактора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Трак',
                'verbose_name_plural': 'Траки',
                'db_table': 'truck',
                'ordering': ['tractor_no'],
            },
        ),
    ]
