# Generated by Django 5.2.7 on 2025-10-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания снимка')),
                ('period_date', models.DateField(verbose_name='Дата периода')),
                ('label', models.TextField(blank=True, null=True, verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Снимок стоимостей',
                'verbose_name_plural': 'Снимки стоимостей',
                'db_table': 'cost_snapshot',
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.CreateModel(
            name='CostSnapshotCommon',
            fields=[
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='snapshots.costsnapshot', verbose_name='Снимок')),
                ('ifta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IFTA')),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Страхование')),
                ('eld', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ELD')),
                ('tablet', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Планшет')),
                ('tolls', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Платные дороги')),
            ],
            options={
                'verbose_name': 'Общие стоимости в снимке',
                'verbose_name_plural': 'Общие стоимости в снимках',
                'db_table': 'cost_snapshot_common',
            },
        ),
        migrations.CreateModel(
            name='CostSnapshotTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_payment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Платеж за трак')),
                ('trailer_payment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Платеж за прицеп')),
                ('physical_damage_insurance_truck', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Страхование физического ущерба трака')),
                ('physical_damage_insurance_trailer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Страхование физического ущерба прицепа')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshots.costsnapshot', verbose_name='Снимок')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck', verbose_name='Трак')),
            ],
            options={
                'verbose_name': 'Стоимости трака в снимке',
                'verbose_name_plural': 'Стоимости траков в снимках',
                'db_table': 'cost_snapshot_truck',
                'indexes': [models.Index(fields=['truck'], name='idx_cost_snapshot_truck_truck')],
                'unique_together': {('snapshot', 'truck')},
            },
        ),
    ]
